### Importing libraries

In [1]:
import anuvada
import numpy as np
import torch
import pandas as pd

In [2]:
from anuvada.datasets.data_loader import CreateDataset
from anuvada.datasets.data_loader import LoadData

In [3]:
from anuvada.models.classification_cnn import ClassificationCNN

In [4]:
l = LoadData()

In [5]:
x, y, token2id, label2id, lengths_mask, class_counts = l.load_data_from_path('/home/sannu/Personal_Projects/data/')

In [6]:
id2token = {v: k for k, v in token2id.iteritems()}

### Change into torch vectors

In [7]:
x = torch.from_numpy(x)

In [8]:
y = torch.from_numpy(np.array(y))

In [9]:
len(id2token)

32898

### Create attention classifier

In [10]:
acf = ClassificationCNN(vocab_size=len(token2id),embed_dim=300,num_classes=len(label2id),
                        word2vec_path='/home/sannu/Personal_Projects/data/word2vec_300_5_5')

In [11]:
from anuvada.utils import save_model, load_model

In [12]:
load_model(acf, '/home/sannu/Personal_Projects/data/model_epoch8.pth')

Model loaded.


In [14]:
# loss = acf.fit(x,y,batch_size=64,epochs=1,validation_split=0.2,run_on='gpu')

### Predicting

Prediction needs more than one minibatch at this moment.

In [28]:
predictions, df = acf.compute_saliency_map(x[-3674],1,'visual.html',id2token)

In [29]:
from IPython.core.display import display, HTML

In [30]:
predictions

array([[ 0.14295784,  0.85704219]], dtype=float32)

In [31]:
with open('visual.html','r') as f:
    text = f.read()
    display(HTML(text))

In [32]:
predictions, df = acf.compute_saliency_map(x[-2398],1,'visual.html',id2token)

In [33]:
predictions

array([[ 0.99127835,  0.00872163]], dtype=float32)

In [34]:
with open('visual.html','r') as f:
    text = f.read()
    display(HTML(text))

In [35]:
predictions, df = acf.compute_saliency_map(x[-2834],1,'visual.html',id2token)

In [36]:
predictions

array([[ 0.97697508,  0.02302495]], dtype=float32)

In [37]:
with open('visual.html','r') as f:
    text = f.read()
    display(HTML(text))

In [38]:
predictions, df = acf.compute_saliency_map(x[-1345],1,'visual.html',id2token)

In [39]:
predictions

array([[ 0.89912432,  0.1008757 ]], dtype=float32)

In [40]:
with open('visual.html','r') as f:
    text = f.read()
    display(HTML(text))